name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-11'
      DEVICE_TREE_URL:
        description: 'DEVICE_TREE_URL'
        required: true
        default: 'https://github.com/rominek75-boop/wp12-twrp-tree.git'
      DEVICE_TREE_BRANCH:
        description: 'DEVICE_TREE_BRANCH'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'DEVICE_PATH'
        required: true
        default: 'device/oukitel/WP12'
      DEVICE_NAME:
        description: 'DEVICE_NAME'
        required: true
        default: 'WP12'
      MAKEFILE_NAME:
        description: 'MAKEFILE_NAME'
        required: true
        default: 'twrp_WP12'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'bootimage'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Configuration
        run: |
          echo "MANIFEST_URL=${{ github.event.inputs.MANIFEST_URL }}" >> $GITHUB_ENV
          echo "MANIFEST_BRANCH=${{ github.event.inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
          echo "DEVICE_TREE_URL=${{ github.event.inputs.DEVICE_TREE_URL }}" >> $GITHUB_ENV
          echo "DEVICE_TREE_BRANCH=${{ github.event.inputs.DEVICE_TREE_BRANCH }}" >> $GITHUB_ENV
          echo "DEVICE_PATH=${{ github.event.inputs.DEVICE_PATH }}" >> $GITHUB_ENV
          echo "DEVICE_NAME=${{ github.event.inputs.DEVICE_NAME }}" >> $GITHUB_ENV
          echo "MAKEFILE_NAME=${{ github.event.inputs.MAKEFILE_NAME }}" >> $GITHUB_ENV
          echo "BUILD_TARGET=${{ github.event.inputs.BUILD_TARGET }}" >> $GITHUB_ENV

      - name: Development Environment Theme
        id: theme
        uses: azwhikaru/Action-TWRP-Builder@main
